services:
  php:
    image: tugboatqa/php:7-apache
    default: true
    commands:
      init:
        - apt-get update
        - apt-get install -y libzip-dev mysql-client
        - pecl install zip
        - docker-php-ext-enable zip
        
        - composer global require "laravel/installer"
